books = [
    {"id": 1, "title": "The Enchanted Forest", "author": "Emma Green"},
    {"id": 2, "title": "Mysteries of the Deep", "author": "John Smith"},
    {"id": 3, "title": "A Journey Through Time", "author": "Alice Johnson"},
    {"id": 4, "title": "The Last Horizon", "author": "Michael Brown"},
    {"id": 5, "title": "Whispers in the Dark", "author": "Sarah Davis"},
    {"id": 6, "title": "Echoes of the Past", "author": "David Clark"},
    {"id": 7, "title": "Beyond the Stars", "author": "Linda Wilson"},
    {"id": 8, "title": "The Silent River", "author": "James Lee"},
    {"id": 9, "title": "Shadows of the Forgotten", "author": "Jennifer Martin"},
    {"id": 10, "title": "A Dance with Destiny", "author": "Robert Garcia"},
    {"id": 11, "title": "The Secret Garden", "author": "Emily Harris"},
    {"id": 12, "title": "City of Dreams", "author": "Charles White"},
    {"id": 13, "title": "The Hidden Realm", "author": "Jessica Adams"},
    {"id": 14, "title": "The Last Guardian", "author": "William Nelson"},
    {"id": 15, "title": "Echoes of Eternity", "author": "Natalie Wright"},
    {"id": 16, "title": "The Forgotten Path", "author": "Joshua Hill"},
    {"id": 17, "title": "Tales of the Unknown", "author": "Olivia King"},
    {"id": 18, "title": "Riddles of the Mind", "author": "Ethan Scott"},
    {"id": 19, "title": "The Lost Chronicles", "author": "Ava Turner"},
    {"id": 20, "title": "The Timekeeper's Secret", "author": "Daniel Walker"},
    {"id": 21, "title": "The Whispering Woods", "author": "Megan Young"},
    {"id": 22, "title": "Voices from the Abyss", "author": "Ryan Allen"},
    {"id": 23, "title": "The Hidden Fortress", "author": "Sophia King"},
    {"id": 24, "title": "Journey to the Unknown", "author": "Matthew Baker"},
    {"id": 25, "title": "Secrets of the Ancient", "author": "Chloe Lee"},
    {"id": 26, "title": "The Enigma of Shadows", "author": "Benjamin Harris"},
    {"id": 27, "title": "The Forgotten Legend", "author": "Isabella Campbell"},
    {"id": 28, "title": "Chronicles of the Lost", "author": "Lucas Mitchell"},
    {"id": 29, "title": "Mysteries Unveiled", "author": "Charlotte Thompson"},
    {"id": 30, "title": "The Eternal Quest", "author": "Henry Carter"},
    {"id": 31, "title": "Guardians of the Light", "author": "Amelia Adams"},
    {"id": 32, "title": "The Shadow Realm", "author": "James Green"},
    {"id": 33, "title": "Beyond the Horizon", "author": "Ella Roberts"},
    {"id": 34, "title": "The Lost Treasure", "author": "Alexander Lewis"},
    {"id": 35, "title": "Echoes in the Wind", "author": "Lily Walker"},
    {"id": 36, "title": "The Timeless Adventure", "author": "Jacob Anderson"},
    {"id": 37, "title": "The Forgotten Kingdom", "author": "Zoe Wright"},
    {"id": 38, "title": "Tales of the Ancients", "author": "Logan King"},
    {"id": 39, "title": "The Mysterious Island", "author": "Grace Hill"},
    {"id": 40, "title": "Legends of the Lost", "author": "Evelyn White"},
    {"id": 41, "title": "Secrets of the Forest", "author": "Samuel Young"},
    {"id": 42, "title": "The Eternal Legend", "author": "Mia Scott"},
    {"id": 43, "title": "The Phantom's Curse", "author": "Ryan Davis"},
    {"id": 44, "title": "Journey Through Darkness", "author": "Sophie Robinson"},
    {"id": 45, "title": "The Hidden Code", "author": "Elijah Nelson"},
    {"id": 46, "title": "Echoes of the Night", "author": "Charlotte Turner"},
    {"id": 47, "title": "The Secret of the Abyss", "author": "Isaac Thompson"},
    {"id": 48, "title": "The Lost Empire", "author": "Lillian Hill"},
    {"id": 49, "title": "Whispers of the Forgotten", "author": "Dylan Campbell"},
    {"id": 50, "title": "The Mysterious Stranger", "author": "Avery Harris"}
]


def get_book_by_id(book_id):
    return next((book for book in books if book["id"] == book_id), None)
